### ISSUE TITLE
exposing port if needed

### ISSUE THREAD

**Issue by iedmrc** [holms/docker-compose-openvpn#1]
Hi,
     expose:
         - "1194"
should be added at least as a comment line maybe for someone needed.
Thank you

**Comment by dan-bolsun** [comment]
Due to this fragment in [docker-compose.yml](https://github.com/holms/docker-compose-openvpn/blob/master/docker-compose.yml) ports are forwarded:

```
ports:
- "1194:1194/udp"
```

As well as in image's [Dockerfile](https://github.com/kylemanna/docker-openvpn/blob/master/Dockerfile):

```
# Internally uses port 1194/udp, remap using `docker run -p 443:1194/tcp`
EXPOSE 1194/udp
```

**Comment by holms** [comment]
As dan said it's exposed in Dockerfile.
